### ISSUE TITLE
Name of project is confusing

### ISSUE THREAD

**Issue by ryancdotorg** [easyctf/openctf#21]
A CTF called OpenCTF has been going on at DEFCON for a long time. Would you please consider renaming your project?

**Comment by mzhang28** [comment]
![image](https://cloud.githubusercontent.com/assets/1700346/22912438/e9ceeb2e-f22a-11e6-8ddd-fa7c83c91484.png)
idk looks closed to me

All jokes aside, I think people will be able to differentiate between OpenCTF the competition and OpenCTF an open-source platform. I hope this doesn't cause too much trouble.

**Comment by remexre** [comment]
Bump; n.b. librectf seems not-yet-taken.

**Comment by mzhang28** [comment]
im fine with this

**Comment by remexre** [comment]
this = librectf?
or this = confusion?

**Comment by mzhang28** [comment]
>this = librectf?

**Comment by mzhang28** [comment]
Changed the name to librectf!
