### ISSUE TITLE
detailed installation guide

### ISSUE THREAD

**Issue by noraj** [easyctf/openctf#31]
Can you provide a detailed installation guide?
With all steps, configuration, etc...

**Comment by mzhang28** [comment]
Hi @noraj1337 
The platform is still under HEAVY construction. When I've finalized the project structure and dev/production environments, I will be sure to release a detailed installation guide. Thanks for your patience!

I'll leave this issue open until then.

**Comment by noraj** [comment]
@failedxyz thanks because a lot of alternative CTF platforms lack this. A good documentation make all the difference between a abandoned project and a living one :)

Thanks for your work

**Comment by remexre** [comment]
Closing in favor of #34.
