### ISSUE TITLE
docker-compose.yml

### ISSUE THREAD

**Issue by noraj** [easyctf/openctf#32]
Why the build paths are like `build: "../server"` in `docker-compose.yml`

Because this isn't an existing path on the host:

```
$ docker-compose up -d
ERROR: build path /home/noraj/server either does not exist, is not accessible, or is not a valid URL.
```

How have I to custom this path:

```
$ cat docker-compose.yml | grep build
    build: "../server"
    build: "../filestore"
    build: "../server"
    build: "nginx"
```

**Comment by mzhang28** [comment]
Your issue made me realize that my current setup was way too complicated. It'll all be in the same folder from now on. I'll leave this issue open until I write docs on how to set it up.

**Comment by remexre** [comment]
Closing in favor of #34.
