### ISSUE TITLE
What license should we use?

### ISSUE THREAD

**Issue by mzhang28** [easyctf/openctf#8]

**Comment by chaosagent** [comment]
Plz no copy.

**Comment by Zer0-One** [comment]
Whichever license will secure more contribution to the project. Probably the Ganoo GPLvSomething

**Comment by nyanpasu64** [comment]
agpl?

**Comment by mzhang28** [comment]
bump

**Comment by remexre** [comment]
Late notice, but Apache2.0+MIT is preferred over MIT due to Apache's patent grant.

**Comment by Ptomerty** [comment]
Okay yes thank you
